import type { ComparisonResponse } from '../types';
import type { LaunchConfig } from '../components/LaunchConfig';
import type { UnitSystem } from '../components/TimeSeriesCharts';

interface Props {
  result: ComparisonResponse;
  config: LaunchConfig;
  unitSystem: UnitSystem;
}

const M_FT = 3.28084;
const MS_FTS = 3.28084;
const N_LBF = 0.224809;

export function FlightCardTool({ result, config, unitSystem }: Props) {
  const imp = unitSystem === 'imperial';
  const rpy = result.rocketpy_results;
  const or_ = result.or_results;
  const params = result.rocket_params;

  const fmtAlt = (m: number) => imp ? `${Math.round(m * M_FT).toLocaleString()} ft` : `${Math.round(m).toLocaleString()} m`;
  const fmtVel = (ms: number) => imp ? `${(ms * MS_FTS).toFixed(1)} ft/s` : `${ms.toFixed(1)} m/s`;
  const fmtMass = (kg: number) => imp ? `${(kg * 2.20462).toFixed(2)} lb` : `${kg.toFixed(3)} kg`;

  // Landing estimate
  let landingStr = '—';
  if (result.hourly_landings && result.hourly_landings.length > 0) {
    const first = result.hourly_landings[0];
    landingStr = `${first.lat.toFixed(5)}, ${first.lon.toFixed(5)}`;
  }

  const handleExport = async () => {
    const { jsPDF } = await import('jspdf');
    const autoTable = (await import('jspdf-autotable')).default;

    const doc = new jsPDF({ unit: 'mm', format: 'letter' });
    const W = doc.internal.pageSize.getWidth();

    // Header bar
    doc.setFillColor(17, 24, 39); // gray-900
    doc.rect(0, 0, W, 22, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text('FLIGHT CARD', 14, 12);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(156, 163, 175);
    doc.text('Generated by RocketBridge', 14, 18);
    doc.text(new Date().toLocaleString(), W - 14, 18, { align: 'right' });

    let y = 30;

    // Motor / rocket summary
    doc.setTextColor(30, 30, 30);
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.text(params?.motor_designation || 'Unknown Motor', 14, y);
    y += 5;
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 100, 100);
    if (params) {
      doc.text(
        `Length: ${(params.length_m * (imp ? 39.3701 : 100)).toFixed(1)} ${imp ? 'in' : 'cm'}   ` +
        `Diameter: ${(params.diameter_m * (imp ? 39.3701 : 1000)).toFixed(1)} ${imp ? 'in' : 'mm'}   ` +
        `Wet mass: ${fmtMass(params.wet_mass_kg)}   ` +
        `Propellant: ${fmtMass(params.propellant_mass_kg)}`,
        14, y
      );
      y += 5;
    }
    doc.text(
      `Launch site: ${config.lat.toFixed(4)}, ${config.lon.toFixed(4)}   ` +
      `Elevation: ${imp ? Math.round(config.elevation * M_FT) + ' ft' : Math.round(config.elevation) + ' m'}   ` +
      `Rail: ${imp ? (config.railLength * M_FT).toFixed(1) + ' ft' : config.railLength.toFixed(1) + ' m'}   ` +
      `${config.inclination}° / ${config.heading}°`,
      14, y
    );
    y += 8;

    // Stats table
    const rows: [string, string, string][] = [
      ['Apogee AGL',         fmtAlt(rpy.apogee_m_agl),                or_ && or_.apogee_m_agl != null ? fmtAlt(or_.apogee_m_agl) : '—'],
      ['Max Velocity',       fmtVel(rpy.max_speed_ms),                or_ && or_.max_velocity_ms != null ? fmtVel(or_.max_velocity_ms) : '—'],
      ['Max Mach',           `Mach ${rpy.max_mach.toFixed(3)}`,        or_ && or_.max_mach != null ? `Mach ${or_.max_mach.toFixed(3)}` : '—'],
      ['Stability Margin',   `${rpy.static_margin_cal.toFixed(2)} cal`, or_ && or_.stability_margin_cal != null ? `${or_.stability_margin_cal.toFixed(2)} cal` : '—'],
      ['Off-Rail Velocity',  fmtVel(rpy.out_of_rail_velocity),         or_ && or_.velocity_off_rail_ms != null ? fmtVel(or_.velocity_off_rail_ms) : '—'],
      ['Burn Time',          `${rpy.burn_out_time_s.toFixed(2)} s`,    or_ && or_.time_to_apogee_s != null ? `Apogee ${or_.time_to_apogee_s.toFixed(1)} s` : '—'],
      ['Time to Apogee',     `${rpy.apogee_time_s.toFixed(1)} s`,      '—'],
      ['Weather',            rpy.weather_source === 'standard_atmosphere' ? 'Std Atmosphere' : 'NOMADS GFS', '—'],
      ['Expected Landing',   landingStr,                               '—'],
    ];

    autoTable(doc, {
      startY: y,
      head: [['Parameter', 'RocketPy', 'OpenRocket']],
      body: rows,
      theme: 'grid',
      headStyles: { fillColor: [17, 24, 39], textColor: [255, 255, 255], fontSize: 8, fontStyle: 'bold' },
      bodyStyles: { fontSize: 8, textColor: [30, 30, 30] },
      columnStyles: { 0: { fontStyle: 'bold', cellWidth: 55 }, 1: { cellWidth: 60 }, 2: { cellWidth: 60 } },
      margin: { left: 14, right: 14 },
    });

    // Rocket diagram
    if (result.rocket_diagram) {
      const imgY = (doc as any).lastAutoTable.finalY + 8;
      const imgW = W - 28;
      try {
        doc.addImage(`data:image/png;base64,${result.rocket_diagram}`, 'PNG', 14, imgY, imgW, imgW * 0.25);
      } catch { /* skip if image fails */ }
    }

    // Warnings
    if (result.warnings && result.warnings.length > 0) {
      const warnY = (doc as any).lastAutoTable.finalY + (result.rocket_diagram ? 30 : 8);
      doc.setFontSize(7);
      doc.setTextColor(180, 80, 0);
      result.warnings.forEach((w, i) => doc.text(`⚠ ${w}`, 14, warnY + i * 4));
    }

    // Footer
    const pageH = doc.internal.pageSize.getHeight();
    doc.setFillColor(17, 24, 39);
    doc.rect(0, pageH - 10, W, 10, 'F');
    doc.setFontSize(7);
    doc.setTextColor(156, 163, 175);
    doc.text('RocketBridge · rocketpy + openrocket comparison', 14, pageH - 3);
    doc.text(`Simulated ${new Date().toLocaleDateString()}`, W - 14, pageH - 3, { align: 'right' });

    doc.save(`flight-card-${params?.motor_designation || 'rocket'}.pdf`);
  };

  return (
    <div className="space-y-4">
      <h3 className="text-sm font-semibold text-gray-200 uppercase tracking-wide">Flight Card PDF Export</h3>

      <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-xs">
        {[
          { label: 'Motor', value: params?.motor_designation || '—' },
          { label: 'Apogee AGL', value: fmtAlt(rpy.apogee_m_agl) },
          { label: 'Max Velocity', value: fmtVel(rpy.max_speed_ms) },
          { label: 'Max Mach', value: `Mach ${rpy.max_mach.toFixed(3)}` },
          { label: 'Stability Margin', value: `${rpy.static_margin_cal.toFixed(2)} cal` },
          { label: 'Off-Rail Velocity', value: fmtVel(rpy.out_of_rail_velocity) },
          { label: 'Burn Time', value: `${rpy.burn_out_time_s.toFixed(2)} s` },
          { label: 'Time to Apogee', value: `${rpy.apogee_time_s.toFixed(1)} s` },
          { label: 'Launch Site', value: `${config.lat.toFixed(4)}, ${config.lon.toFixed(4)}` },
          { label: 'Expected Landing', value: landingStr },
        ].map(({ label, value }) => (
          <div key={label} className="flex items-center justify-between py-1 border-b border-gray-800/60">
            <span className="text-gray-400">{label}</span>
            <span className="text-gray-200 font-mono">{value}</span>
          </div>
        ))}
      </div>

      <div className="flex items-center gap-3 pt-1">
        <button
          onClick={handleExport}
          className="flex items-center gap-2 bg-blue-600 hover:bg-blue-500 text-white font-semibold px-4 py-2 rounded-lg transition-colors text-sm"
        >
          <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
            <path strokeLinecap="round" strokeLinejoin="round" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
          </svg>
          Download PDF
        </button>
        <span className="text-xs text-gray-600">Includes rocket diagram, stats table, and warnings</span>
      </div>
    </div>
  );
}
